# Generated by Django 5.0 on 2025-10-03 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviepetition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviepetition',
            name='user',
        ),
        migrations.RemoveField(
            model_name='moviepetition',
            name='votes',
        ),
        migrations.AddField(
            model_name='moviepetition',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitions_created', to=settings.AUTH_USER_MODEL, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='moviepetition',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='MoviePetitionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.moviepetition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='moviepetition',
            name='voters',
            field=models.ManyToManyField(related_name='petitions_voted', through='movies.MoviePetitionVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='moviepetitionvote',
            constraint=models.UniqueConstraint(fields=('petition', 'user'), name='unique_vote_per_user_per_petition'),
        ),
    ]
